apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-dep
  labels:
    app: {{ .Values.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
      - name: go-web-app
        image: saymapatwekar/go-web-app:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
