apiVersion: v1
kind: Service
metadata:
  name: go-app-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app_name }}
  ports:
    #svc port
    - port: {{ .Values.service.port }} 
      #container port
      targetPort: 8000
      nodePort: 30007