app_name : go-app

#deployment
replicaCount: 1
image:
  name: saymapatwekar/python-web-app
  repository: nginx
  pullPolicy: IfNotPresent
  # get updated via jenkins as per latest image tag
  tag: "v1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

#service
service:
  type: NodePort
  port: 80

#ingress
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: sample-app.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

